### ISSUE TITLE
change the script name buid.sh to builder.sh [not major issue]

### ISSUE THREAD

**Issue by 4riful** [0xJin/awesome-bugbounty-builder#5]
as in the installation process there is " chmod +x awesome-bugbounty-builder.sh"
but the script is named like awesome-bugbounty-build.sh . Although its not an major issue

**Comment by 0xJin** [comment]
Is not important , but thank you anyway :)

**Comment by 0xJin** [comment]
thanks

**Comment by 4riful** [comment]
Yeah already said that it's not important ☺️! But what you have been doing is really amazing brother! Take a bunch of love
