### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by blackkhawkk** [0xJin/awesome-bugbounty-builder#7]
amass enum -brute -passive -d exampple.com | sed 's#*.# #g' | httpx -silent -threads 10 | xargs -I@ sh -c 'ffuf -w wordlist.txt -u @/FUZZ -mc 200'

amass enum -brute -passive -d https://
![Selection_133](https://user-images.githubusercontent.com/60282451/147921102-571c94dc-08eb-4cb9-925f-c57adf2fed0d.png)
yodlee.com | sed 's#*.# #g' | httpx -silent -threads 10 | xargs -I@ sh -c 'ffuf -w wordlist.txt -u @/FUZZ -mc 200'

showing command no found.

Please help

**Comment by 0xJin** [comment]
Bro remove $ please

**Comment by 0xJin** [comment]
and wordlist use your wordlists!!
