### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [0xJin/awesome-bugbounty-builder#8]

**Comment by 0xJin** [comment]
what is your error?

**Comment by sasholy** [comment]
amass enum -d testphp.vulnweb.com | httpx -threads 300 -follow-redirects -silent | rush -j200 'curl -m5 -s -I -H "Origin: evil.com" {} | [[ $(grep -c "evil.com") -gt 0 ]] && printf "\n3[0;32m[VUL TO CORS] 3[0m{}"' 2> txt.txt

inside the file - rush: invalid option -- 'j'

**Comment by 0xJin** [comment]
Is not "--j" instead not use -j200

**Comment by 0xJin** [comment]
Is not "--j" instead not use -j200

**Comment by sasholy** [comment]
sudo amass enum -d testphp.vulnweb.com | httpx -threads 300 -follow-redirects -silent | rush 'curl -m5 -s -I -H "Origin: evil.com" {} | [[ $(grep -c "evil.com") -gt 0 ]] && printf "\n3[0;32m[VUL TO CORS] 3[0m{}"' 2 > txt.txt

You are not permitted to execute this command.
Contact the systems administrator for further assistance.

kali linux
